language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: XpPhXaVMEJz6IcRwpDeQl5jz36UqZESN7t91Dg3vXwGh76j6E5BWHZtmbjGzQJAWRfjad6Y9MVUBfFFvfnwmYzSDxzKEB8MZUUYRZxWXZTk4T90mvLOLwGFkXhFJ1nEvBhHsfI34j7pDOQmJOTLQRrhM9bChjoHyrTbFe3WyvrxaUufkKEnC671f1LPJRaqSVPtZp8elu7JZSmJDiKbgwqkwaMMdhk3JZf9/Y7PF6BwERZQDZEvwa2IngjdWcAuQ7arvIJvP8mVMRRlIobZEgb3yumGzSFoOb45ERuVTJr4dgAtebsCcleaiVD5LXSzkPcL6s634HETfJpnjpvNCA9H6CWisTEaa3UMqlTu8KxAtLvrBjT8BC9kj3DIj5VvfPTqTSMqNB0J2OdrcSzvwv+8ywL+mjVbn1UeUnFjdAD/g0/aEf4a6Efe9xiL1lXTLkqVgITMAkmawmSmznh4vH/SVW9UqZW9FHHuuEUBTI1Rcrnqp8ozCV94EIeJUAM8eZi8Jhv9wWA47+ZayXjmcfRVBOB5SsGCZvHdcnjeIXTGopMMRq9E9ykpPq15Sf0tPVUxCM0lDv2g6HxCZkRY0Q9Pgf8rl6XMh8+o0nPxaLgKWjqJ+WgvSTAajammniwY4wu2zfS205M4e5y646wBDk1TAhwq5BwIDvNMSXYJ6AUA=
  app: auto-vpngate
  on:
    repo: lqflqf/auto_vpngate
  skip_cleanup: 'true'
