language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: Tt6w3K34bUIy/c4cE0NwLQd+EXzAHSBWzxXHER8mtpJJaqkr4ic6Z/S2EE7sGRYLV93XJ2NWTpIVLZLo0X3wgvVRHixTEGA4eKhAfDAnBT4SlOWhdM/QSGEIPhuqgBH94c2LFI8FW8S2Q3aRGFnt7EQD/eRh7cCnumLBXufH7oAFaYGcXIxydw44jtkOm6h9bnTxVflDFtjiIEDtBbV9shx/HajTQtosVFJoP5DbL9UYzdACkrH2tFt3lCDQFPjT3kJNAiJ7gldJbzJU7usPxp0V4Lod86Bls7l4Lz3filg078ID5oN0exncpByqBplHPs6EGWmadVTzyr9nYwZuitq0iPd51j6IVNTIGhPYPuezEDkLsC7+4h8jp15IeeE5eCZmUczdxX/FjzzWMzA6XDynPh89v7NdAjSV/olJt0W0DQjO/OuPiNKQxRQ6R56z/JSitpaLL0zrsWYqL6SmVKfWSjCv7kbkH3bPMJEv0ScFWdc5mNkMVKsjX1xuBsi6OrPGXc4JBV9eO/vzhAiw3tIp9zUDr/9Q5+cLpTpC6cTB4df7A9zdza0d0QliB98OVfbrpeIwbh0SrFwYXnnjPah4fC3QwFUndTXdJVYM439zR1PJL0JOlaTW2+c1kBCGATRzGzlCJdN/TLyvqvpGbbRz8f8NKQtLn//MKf7jEZ4=
  app: auto-vpngate
  on:
    repo: lqflqf/auto_vpngate
  skip_cleanup: 'true'
