language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: RALWcsuYM2b65yq6LDfWcwuwhQfICd+5hQXPZi/G3lcz5Jo2HCB7RiuhGTFq/v4Mc560SEm3CHise3aLcHm+xjJLeZfFb1w85Bz2CX8Dg7Pmb63Hbm5KBCpa7/RaPl6mNZWWqSnAYPkDKZOtCf2hCm0829PYKKI91MI8npYixk8OaN0R7+BQZGbPeAmjHrSECVI52TZVDfKnWcGHFS528mHy88qS28tUhHfX2+kmXFqP5Lg3dmDhbx3hggf/Ppb6QZI293fbRKitL3XSaOm4UEqqK/1xTDcL0IMpDcjgyWr1u8JscGFva3beVdDJAfhB//VLQZMkhIgVXh2WPp8M4ZYUOIsZh1VpXk9TUCW4GSMYerLSSEiZOJyVai5a2bU4AmotjINIjNdy6m+Owu7kFvv/JMAfE/htTZD+w5Iv1i8VLDaIjuxcpdRjMfXUMYX8qQ9po+NxJMsfXp7yiojp2gaH1ZuCrWi8LxVEMJlf7r4kqEXqTdlCKAyXBrKsI9gTPqRmphnuIs0RbzI9tq6TzuboCKKRSlpCD+lcWTrIbkgKkiF42QFnLHNgJyb+ng840zMUAAZt3QKWIF6bFAfoYFml8z5OrEtVeWf79CFoxw9eYsPtuosQp6kWw+KyYEeuZy6bQUYYmU1D35qoNYm2F8pAMtGGSC+5i3ugfGOUn14=
  app: auto-vpngate
  on:
    repo: lqflqf/auto_vpngate
  skip_cleanup: 'true'
