language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: MccLzZBPD0i9t7c9IqMS4gk0Qe1vZbYMaacJVNe5aC1Jtc2ZbQAG15PM0VLwKp6nr82ObQR4SIGMia1ZZOQPUZF1NgNDlNBDSpLOisJZW5UCXzEWS8WW3ZghrGjy89JncQN4Pj4AZL4/he74qDXravASoiuhIFHwHKlXj9rtkGnlIb6bR4aGmTMCuE63HpQZ9bx0HE6doAl+7JI4Irh+/zSkEoCepO5s+EvVnBU+1gGeTaO26fjYV3y2jP1ZpYWvVsUabAd1iDmy7qhW8S36JDdxALEvcEX7/G3NJfPyiUnO5UPK7+D96PXSIbpqclaSFeyKPNkhcIGx7kXi5cfDU/Q2FGtpMGEi57627QY+bIKUOkO7rVKyjNMh00JwFsy7E5x55slNNO4CeYNUnM2ByNQm6xv6scrq8FmxqcxHsXbHyTIObIaFRMByjwq82cYqqkdmpnzikooWgbwpGLnulwP6CU0i9bMhpNKHFM6FlEGSAKaKIMyqs+B3LbEHbw7Y99qO36eVgNXRiyPSHsS8NB1URZLID6KNwkAC2BemmCf2UWYrG/CnELDCyXwGQ/TMYoR84ZTtdH5jaHUFDIfdpKP7nAXq6kRyE+AZq0wdt8vGu0+fPV8STPt9vOIbMFePB1E4/WF7pmYbdkYIhrrQ3d+whMyXSTX49U/3xWjVw2A=
  app: auto-vpngate
  on:
    repo: lqflqf/auto_vpngate
  skip_cleanup: 'true'
