language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: nYiqQrLzj5XSGdjZYRlFamJjrd+GmZAER88uChO6XD3gBZoXh53luQ6Tjqb9MIW1ySdIel1pxYJ4Y5iYxydAaaIWPdc9dTlvaJ5bJPf5rkvf10TmkL3mkxlPBUg63Qn8ApO2WFrw7J2NAKnZ8CJQ7432ErUpNvKKxIzpi8z9LW9HPcmS+uZrnxQrweaNTc4KnpkNleEENloa6R6gyKQ1MtXspOPeIWt+9Dvdiovp9E0nM7gHjMfzD5koV08DmJsfLuscebccWhhhPsj2F+Rkpgf0vc7WxN85uZz237H2eWIoJ/6vUHTyLr4Y+d7ZvhnRNJLZ4xay/doBziYDjtDp29+r0XZ1nQ8alFrJEEyZrk0eWj7+4r0IpPnYn0+1TNQR45RNdWQ6eAvuth85KQavoZdd98YGJZBr0FYENia45SIqCF/+3u4oKuJd/pm9lfIXj2iMdmMMbeRUjTxyfGKsK++Ki6qZ08ylMpRTbzvKhKKnT4aJ+xt617tSYm6VEa3p81pPrFCc6Eo99wfEmdfncdPkYgr1BMGx8EDNK4uv6ORpnET//u63TaPE6WiQ0rL32jLWvhL47I4j4RXHfZVOZ56z7mc97aqNGlGsVM8vjhG/0Da04z0m2yl+wAYROmnIylR5clOfjtsy3x/ZfAgEMYOLb+qUIU/FyTZCElbeG4k=
  app: auto-vpngate
  on:
    repo: lqflqf/auto_vpngate
  skip_cleanup: 'true'
