language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: bW/o6WwKCyS4TI0HDhkHVcd1R3DjoRuefFPzLgcQhYX1z5A0ZASG0cEppBMZkdf0We0o+PQ4qcGqc+Y0up6x+ay4m0Mr80EXM1PydtGvKk7WPDADmIob7xTR7dn6Y0ZTibijdCDQiDjFkgMyaGvTkDaVYQ6o46esXog7DvsLJyn/yf1xSy5A2zkG3g9lftxZt+69CLSlSTaDiKqb8mZzM+2TAf60bJhWrlpLFrHI+Ya9tGtohQR/SSRP6F4sdP2YEzGZgDNDhF7gh+QtvhpAs3Saw2Vdku76Fz8GxYMkML/Tp3x6DgI6AX66/KOBePddB2yW6NIFItg9tsGD+UqtvYwy7veOV3LPJDSYNrqNi3Fxy2czNqulw18aiLTqTwADTeAl/mrch5RVhny4z0yH5QMg3+p46gW54oS13DAmUYb/jK83gAHGq3kUkmfh61LpF7SkMQSxeFf+LCyYP3fJoBkf8jJbv4s/B0GDDq5Ip/o5jOlhR27TXk6rZycw0X+eVRAB8uhEYp0k0ITCa4z25ytzArOAJujw7Iif4de8XoTAqlbyuGrXwPm8D6Vijq60mYOSBDXiZlCVJCzsoGWn2LvZ7L+oSX47AzNfwfUbWc5IlvLjvHYvoiiYQjqUQJCXHy5qSvQFrgj3DrCtR0svVwJQdNPn4CA05KENArklH7E=
  app: auto-vpngate
  on:
    repo: lqflqf/auto_vpngate
  skip_cleanup: 'true'
