language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: rW3VdCckK6gBYpFFq9/n3SK8dDePhaRFtnwEouTK4v8w0h6ObHs9PiUdpFz3g8u//Mj+AAe6xPK8olZNGHinOQZlkqCVRWJlTPMfSEFZOfzP77l/BOh5ckiG+PfR+Bbf+7Qp1wuSJHp3FYiA1YQkTC/j5shpEDYjz05dTF8WI1SSgLeEyXW92fWP4lYpOzSK9JDhmxcKwpIgMgOFj2RhJNX8EDsoZWSViEvzSfWZ8Yz7HuHck1cRzOlYcppCOJhZ1GtshbyjS/nrWG68Z7NuegxHYLGpj5CYWlMYPImTnPt/MMEVHJke/WnuIz5Hl49Gf/H0oPvYqXwlXv4ssIoe6WG8UG5AsiZ36qRI8d5WSsjvCfLTpPW61SzOaG66Bi3+yMTQmSbiYX3BWHFSNnlVH9X9z9r0gCnM9WF1GkUvwTsLvcDfs9IQKrmMVUvWCDau7stEwUZzw01FrNkJ3DpNKqT9Bv03byt53oBWmbxcuZWAUL75A1ClhGwjrzZwGQ2mVRH09qyTixNjZj4El/zpwFLYm2rrHRyNUcJGpWfajo61j5a+CuiIa2DYOxmhI0SPfEM7Hn5zEbkrcPvh6sjyAaydAIl28EavjtP8apBrlWl6v1fBGz/ZJvv0GMs67jXidYbZd5GXBFDzxV4fCfCO41sBoeZNP0C0dbGiPgFMDiU=
  app: auto-vpngate
  on:
    repo: lqflqf/auto_vpngate
  skip_cleanup: 'true'
