language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- pytest
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  api_key:
    secure: b8DYQOV1P0WC0QSoq9RuDtxpGtBRCwuxghgLS9aW8hy74cmS+jmiXtM8R58jI6w5TcSS7i6ETpP66sx+9kIgIleLsE0tfYpKXHP5QNhRHxu94BrgwEjAMLkfdD2i+mTxf7CXO2EhJ4pisGV0moKQ+Z6Svg7MZ4dY6xXmQV2AVxFpkrAkAL4fyC3A9lgszfM3e/S+cc09jt4CzByQLBx6cEnUSnXnMTCYlT6cHHm/FKPPvgLfZb14IWvR4Ql3SjFQVEsb7jnDWr3+PDCoPi9+h37XxhDEMyOL1SkdqbDs5pWhALrXPP0i1z9w7KLRIK+IxVIfVZtdoLTdOSBLftinun8vmTR+40kob4UiV1tTybIZpcfsTQuDJ5ljtAFOZt6Bjyx0wUc7PI1bFCgNtsG1L/Gjllh4MYqvWEi+UiRodxHIa+WcLpahchujm2Hx1ZNLyeLSdLylZpVnnWxIV6cIq/7fvY+dbGPVl1B8YDLH574TXJCLVIUP61dzhRKLRdMj3uF3Qwk+tyuEMZbKcUBiDoaW37ln0vEV2o7A0WVR9+PpvNrPb/9eSUtFgQQI2qoipW0z1Y5QKMzh6/Ju57F5t/4Z6h9CxCzxe99WdE5xZcCAcWjk8mcyUeYV0WEnMPQy1KodarnHoEsnYVTmFMpsgoeNxMlnlGSUoJ2jUhOoI44=
  app: auto-vpngate
  on:
    repo: lqflqf/auto_vpngate
  skip_cleanup: 'true'
